### PR TITLE
Required `secret` param isn\'t set (php 7)

### PR DESCRIPTION
**Pull request by ghost**
When i update my local php from 5.6 to 7 i got this error, because !empty( Yii::$app->reCaptcha->secret;) - rerutns only FALSE

### CODE REVIEW

**Comment by CyberPunkCodes** [comment]
When testing locally, Google doesn't require the sitekey or secret, so that we CAN TEST. This is a flaw in the latest version of this extension.

This extension should check if we are running Yii in dev mode before requiring that we provide the sitekey or secret.

**Comment by boutmine** [comment]
Wade whats up man hit me up on skype.  @WadeShuler

**Comment by CyberPunkCodes** [comment]
send me your username, I don't have my old skype.

**Comment by boutmine** [comment]
hey its harrismarketing or use my email its harrismarketing1@gmail.com or ccuttabeatz @WadeShuler

**Comment by ghost** [comment]
ok then, PHP 7 empty() function work really bad when works with magic methods.
therefore we have __isset() in our main(yii2) sevice locator that don't work in php 7.
there is two solutions 1) update all service locator childs adding __isset() method OR
2) don't use yii2 with php 7
And my solution is easy as f*ck just before we check !empty(yii::$app->reCaptcha->siteKey) 
put  this magic method in variable yii::$app->reCaptcha->siteKey => $siteKey = yii::$app->reCaptcha->siteKey. Thats it, and all of us will be happy

**Comment by boutmine** [comment]
hey wade add me on skype my username is harrismarketing1@gmail.com  @WadeShuler

**Comment by gitdevhub** [comment]
hello. when you accept request?

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-recaptcha-widget/pull/37

**Pull request closed without merging**
